export const PRODUCTS = [
  { id: 1, img: 'A2.jpg', 
    name: 'Hiking  - NH Escape 500 Gustore production', 
    description: 'Our motivation? To provide a comfortable and accessories. Your best daily companion  Your best with its 3 compartments, 14 pockets and smart functionsprovide a comfortable.', 
    price: 220.99, discount: 10 },
  { id: 2, img: 'A3.jpg', name: '30L Hiking Arpenaz 500 isothermal original USA'
   , description: 'Full of surprises, this hiking backpack also has an isothermal compartment to keep your picnic cool. backpack also has an isothermalThe removable rug will keep you dry when eating.'
    , price: 225, discount: 15 },
  { id: 3, img: 'A4.jpg', name: 'Hiking backpack 35 L - NH Escape 500'
   , description: 'This hiking bag is comfortable with its padded pads, practical with its 3 compartments and 15 pockets and smart thanks to its cabin size and clever features.', 
    price: 118, discount: 20 },
  { id: 4, img: 'A5.jpg', name: '30L Hiking Backpack NH Arpenaz 500 isothermal'
   , description: 'Full of surprises, this hiking backpack also has an isothermal compartment this hiking backpack to keep your picnic cool. The removable rug will keep you dry when eating.', 
    price: 12, discount: 5 },
  { id: 5, img: 'A6.jpg', name: '22 L Rolltop Mountain Hiking Backpack - MH500 Light Green', 
    description: 'This versatile bag has a 22-litre capacity, rolltop opening and multiple pockets. Its foam straps and design that conforms to your movements provide optimal comfort.', 
    price: 190, discount: 8 },
  { id: 6, img: 'A7.jpg', name: '20 L Hiking Backpack - NH100 Arpenaz - Blue', 
    description: 'This 20 L bag has all the essentials for hiking: 2 zip pockets, a large compartment, 2 bottle holders and awater bladder separator for a 15” PC or water bladder.', 
    price: 178, discount: 12 },
  { id: 7, img: 'A8.jpg', name: '20L Hiking Backpack - NH Arpenaz 500', 
    description: 'With its padded straps and thick, ventilated pads on the back, this hiking backpack is comfortable to wear. Very robust, it’s suitable for your lowland walks.',
     price: 14, discount: 18 },
  { id: 8, img: 'A9.jpg', name: 'Hiking Backpack 16L+4 NH500 Escape RollTop - Beige', 
    description: 'Explore without limits with this versatile backpack! Ingenious RollTop: go from 16 L to 20 L in the blink of an eye. 8 clever pockets, including a 13" PC / water bladder space.',
     price: 229, discount: 7 },
  { id: 9, img: 'A10.jpg', name: 'Climbing Backpack 20 Litres - ROCK 20 Ocre',
     description: 'Developed with our team of athletes, it has all the features to make life easier for multi-pitch climbing: a large front pocket, quick Easy Access opening, helmet holder, etc.', 
     price: 125, discount: 25 },
  { id: 10, img: 'A13.jpg', name: 'Computer Backpack Mens Backpack - Blue',
     description: 'Product information: Pattern: solid color Lining texture: Polyester Applicable scenario: leisure travel Color: gray, black, blue, red Applicable gender: neutral/both men  ', 
     price: 125, discount: 15 },
  { id: 11, img: 'A18.jpg', name: 'New Nike  Panda Black White (DD1391-100)',
     description: 'Nike Dunk Panda Low Retro Shoes Sneakers - Black/ White (DD1391-100). SIZE - US 7 (25cm) - US 12 (30cm)The worlds premier sneaker and apparel marketplace..', 
     price: 125, discount: 20 },
  { id: 12, img: 'A14.jpg', name: 'Stadium Goods - The Latest Sneakers & Premium Apparel', 
    description: 'DESCRIP :The worlds premier sneaker and apparel marketplace. We sell the most sought after shoes, streetwear and accessories from Nike, Jordan, New Balance, and more.'
     ,price: 229, discount: 7 },
  { id: 13, img: 'A15.jpg', name: 'Jordan 1 High Travis Scott Release Date',
     description: 'The worlds premier sneaker and apparel marketplace. We sell the most sought after shoes, streetwear and accessories from Nike, Jordan, New Balance, and more', 
     price: 125, discount: 15 },
  { id: 14, img: 'A16.jpg', name: 'The Nike Air Jordan I Receives the Pine Green Treatment',
     description: 'The Nike Air Jordan 1 gets done up in a brand new “Pine Green” colorway. Find out here how to secure yourself a pair when it drops September 22,New Balance, and more', 
     price: 125, discount: 12},
  { id: 15, img: 'A17.jpg', name: 'Nike Air Jordan 1 Low Wolf Grey Midnight Navy',
     description: 'Nike Dunk  Low Retro Shoes Sneakers Купите Nike Air Jordan 1 Low Wolf Grey Midnight Navy в интернет-магазине NikitaEfremov.out here how to secure yourself', 
     price: 125, discount: 10 },
  { id: 16, img: 'A19.jpg', name: 'New Nike Dunk Low Retro shipping options at checkout.',
     description: 'Created for  hardwood but taken to the streets, the Nike Dunk Low Retro returns with crisp overlays and original team colors. This basketball icon channels 80s vibes with premium leather in the upper that looks good and breaks in even better. Modern footwear technology helps bring the comfort into the 21st century.', 
     price: 125, discount: 15 },
  { id: 17, img: 'A20.jpg', name: 'Nike Air Max Nuaxis Premium You see shipping  at checkout.', 
    description: 'Breathable and comfortable, the Air Max Nuaxis is ready for everyday life. You can count on it to look good and feel good too. It combines an intuitive Air unit with design elements inspired by the Air Max 270, making the perfect shoe to lace up and go.the Air Max Nuaxis is ready for everyday life. You can count on it'
     ,price: 229, discount: 7 },
  { id: 18, img: 'A21.jpg', name: 'Nike Dunk Low JP You ll see our shipping options at checkout.',
     description: ' after shoes, streetwear and accessories from Nike, Jordan, New Balance, and moreYou can always count on a classic. The Dunk Low pairs its iconic color blocking with premium materials and plush padding for game-changing comfort that lasts. The styling possibilities are endless—how will you wear your Dunks?', 
     price: 125, discount: 8 },
  { id: 19, img: 'A22.jpg', name: 'Air Jordan 9 G NRG  see our shipping options at checkout.',
     description: 'When MJ hits the open highway from his hometown to the historical golf haven among the crisp pines and aged cedars in the Carolina sand hills, theres often a succulent cigar perched between his fingers. This special AJ9 nods to MJs pre-round routine, complete with cigar-shaped lace tips, rough textures that mimic the road', 
     price: 125, discount: 20},
  { id: 20, img: 'A23.jpg', name: 'Nike Air Zoom Spiridon Cage 2 our shipping options ',
     description: 'First released in 2003, the Nike Air Zoom Spiridon Cage 2 is as relevant today as it was back in the day. A full-length, arched foam midsole and caged Air Zoom unit deliver optimal cushioning, while durable traction pods on the outsole provide grip and stability. Slip into a responsive ride in Y2K style.', 
     price: 125, discount: 25 },

];
